name: Backend CI/CD

on:
  push:
    branches: [ "main" ]

env:
  DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
  IMAGE_TAG: ${{ github.sha }}

jobs:

  # CI JOB
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Cache Maven
      uses: actions/cache@v3
      with:
        path: ~/.m2
        key: maven-${{ hashFiles('**/pom.xml') }}

    - name: Set up JDK
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '17'

    - name: Build all services
      run: mvn clean package -DskipTests

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build & Push Images
      run: |
        SERVICES=(
         "founderlink-config-server"
         "founderlink-service-registry"
         "founderlink-auth-service"
         "founderlink-user-service"
         "founderlink-team-service"
         "founderlink-startup-service"
         "founderlink-investment-service"
         "founderlink-notification-service"
         "founderlink-api-gateway"
        )

        for SERVICE in "${SERVICES[@]}"; do
          docker build -t $DOCKER_USERNAME/$SERVICE:latest ./$SERVICE
          docker build -t $DOCKER_USERNAME/$SERVICE:$IMAGE_TAG ./$SERVICE

          docker push $DOCKER_USERNAME/$SERVICE:latest
          docker push $DOCKER_USERNAME/$SERVICE:$IMAGE_TAG
        done


  # CD JOB
  deploy:
    needs: build-and-push   # ensures CI finishes first
    runs-on: ubuntu-latest

    steps:
    - name: Deploy to VM
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.VM_HOST }}
        username: ${{ secrets.VM_USER }}
        key: ${{ secrets.VM_SSH_KEY }}
        script: |
          cd ~/founderlink
          docker-compose pull
          docker-compose up -d --remove-orphans
          docker image prune -f